import React, { FC } from "react";
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Results from '../components/Results'
const temp_url = 'https://api.musixmatch.com/ws/1.1/track.search'
const API_KEY = process.env.API_KEY

const Home: FC<any> = ({ results }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Results results={results} />
    </div>
  )
}

export async function getServerSideProps(context: { query: { q: any; }; }) {
  const url = `${temp_url}?q=${context.query.q ?? ''}&apikey=${API_KEY}`
  const request = await fetch(url).then(res => res.json())
  return {
    props: {
      results: request.message.body.track_list ?? 'Nothing found'
    }
  }
}

export default Home